Lesson4.setting environment
IgorSharov/thinknetica-react-isharov pull request #4
Opened 2017-12-06 20:34 UTC by IgorSharov

- Создана директорию src в проекте блога, а которую перенесены все исходные файлы проекта;
- Исходный код проекта декомпозирован на модули;
- Созданы компонент приложения (App.js) и точка входа в приложение (index.js);
- Настроено рабочее окружение с горячей заменой кода (с использованием babel.js, webpack и react-hot-loader);
- Выбран и подключен UI-фреймворк - Semantic-UI-React;
- Установлен и настроен линтер ESLint.

2017-12-07 15:19 UTC, blackleadsu requested changes
Следует убрать dist из репозитория.

2017-12-07 15:19 UTC, blackleaden commented on .eslintrc.js
> +module.exports = {
Следует исправить все ошибки, которые выводит линтер. Их можно посмотреть в консоли:
`./node_modules/eslint/bin/eslint.js ./src --ext js,jsx`

2017-12-07 15:19 UTC, blackleaden commented on src/components/ui/BlogList.js
>  import _ from 'lodash';
лучше `import { map } from 'lodash'`

2017-12-07 15:19 UTC, blackleaden commented on src/components/ui/BlogItem.js
> +      { ...metaData, onLikeClick: () => onLikeClick(id) })
"соединить" id и onLikeClick можно еще на уровне BlogList. Тогда id в компонент можно вовсе не передовать.

2017-12-07 20:34 UTC, IgorSharov commented on .eslintrc.js
> +module.exports = {
Проверил с ключом --fix. Ругнулся только на `PieChart.js`:
```
   2:8   error    'DOM' is defined but never used           no-unused-vars
  12:29  warning  'columns' is missing in props validation  react/prop-types

? 2 problems (1 error, 1 warning)
```

2017-12-07 21:03 UTC, IgorSharov commented on src/components/ui/BlogItem.js
> +      { ...metaData, onLikeClick: () => onLikeClick(id) })
У меня на уровне BlogList генерируется key, учитывающий валидный пришёл объект или нет (id<0). Если перенести на этот уровень событие клика, то будет ошибка при клике по лайку объекта-заглушки. Если не критично, то я оставлю так.

2017-12-08 07:22 UTC, blackleaden commented on .eslintrc.js
> +module.exports = {
на то он и fix:)

2017-12-08 07:26 UTC, blackleaden commented on src/components/ui/BlogItem.js
> +      { ...metaData, onLikeClick: () => onLikeClick(id) })
не критично, просто это хорошая практика -- нужно чтобы ты учитывал эту возможность в будущем.

2017-12-08 07:26 UTC, blackleadsu approved these changes

2017-12-11 08:16 UTC, merged